# runme.R ----
# Bootstrap script for this manuscript template.
#
# Run this once after cloning to check dependencies + folder structure,
# then build the analysis pipeline and render the manuscript.
#
# This script does NOT scaffold a new Quarto project — the project files
# (index.qmd, _quarto.yml, etc.) are already part of this template and are
# version-controlled. Re-running quarto::quarto_create_project() here would
# overwrite your customised YAML/content, so don't.

# 1. Check required packages ----
required_pkgs <- c(
  "targets",     # pipeline
  "tarchetypes", # tar_quarto() and friends
  "quarto",      # render + project helpers
  "tibble",      # used by the example target — swap/extend as needed
  "here",        # anchors file paths to the project root everywhere
  # Used by supplementary/tables-mre.qmd — drop these if you delete that
  # notebook and don't need cross-format table comparisons.
  "kableExtra",
  "gt",
  "flextable",
  "huxtable",
  "DT",
  # Used by supplementary/images-mre.qmd and generate-images.R — drop these
  # if you delete that notebook and don't need cross-format image/diagram
  # comparisons. Mermaid diagrams need no extra R package (Quarto handles
  # those itself), but note docx SVG embedding also wants a system
  # `rsvg-convert` binary (librsvg) on PATH — see the notebook for details.
  "ggplot2",
  "magick",
  "svglite"
)

missing_pkgs <- required_pkgs[
  !vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)
]

if (length(missing_pkgs) > 0) {
  message("Installing missing packages: ", paste(missing_pkgs, collapse = ", "))
  install.packages(missing_pkgs)
}

# 2. Ensure folder structure exists ----
# R/                    - custom functions, sourced by _targets.R via tar_source()
# manuscript/           - self-contained Quarto project: index.qmd, its own
#                         _quarto.yml, tables/, figures/, supplementary/,
#                         styles/, img/, references.bib (all tracked in git)
#                         — see "Directory layout" in CLAUDE.md/README.md
# data-raw/             - raw, as-received data + import/cleaning scripts (tracked)
# data/                 - processed data produced by the pipeline (git-ignored,
#                         regenerated by tar_make() — see data-raw/README.md)
# output/               - rendered manuscript (html/docx/typst), git-ignored,
#                         rebuilt by tar_make(). Quarto's website render deletes
#                         anything under here it doesn't recognize as its own
#                         output — don't write anything else into this
#                         directory (see submission/).
# submission/           - standalone per-table/per-figure exports for journals
#                         that require individually named files
#                         (tbl-01-*.docx, fig-01-*.tif, ...), git-ignored,
#                         rebuilt by tar_make(). Deliberately NOT inside
#                         output/, for the reason above.
required_dirs <- c(
  "R",
  "manuscript", "manuscript/tables", "manuscript/figures",
  "manuscript/supplementary", "manuscript/styles", "manuscript/img",
  "data-raw", "data", "output", "submission"
)

for (d in required_dirs) {
  if (!dir.exists(d)) {
    dir.create(d, recursive = TRUE)
    message("Created missing directory: ", d)
  }
}

# 3. Sanity-check the Quarto install ----
# Fails loudly and early if Quarto CLI isn't on PATH, rather than deep into
# tar_make().
quarto::quarto_version()

# 4. Run the targets pipeline ----
# Builds all data/model/figure targets AND renders index.qmd, since a
# tar_quarto() target is wired into _targets.R.
targets::tar_make()

# 5. Inspect pipeline status ----
# Handy after tar_make() to confirm what built and see timings/dependencies.
targets::tar_visnetwork()
